//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_ShowRoom_Manager_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sale
    {
        public int SaleId { get; set; }
        [Required]
        public Nullable<int> VehicleId { get; set; }
        [Display(Name = "Show room name")]
        [Required]
        public string RoomName { get; set; }
        [Required]
        public Nullable<int> CustomerId { get; set; }
        [Required]
        public Nullable<int> AdminId { get; set; }
        [Required]
        public Nullable<double> Price { get; set; }
        [Required]
        public Nullable<System.DateTime> OrderDate { get; set; }
        [Required]
        public Nullable<System.DateTime> DaliveryDate { get; set; }
        [Required]
        public Nullable<int> Status { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
