//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_ShowRoom_Manager_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VehicleImg
    {
        public int ImgId { get; set; }
        [Required]
        public Nullable<int> VehicleId { get; set; }
        [Required]
        public string ImgPath { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }

    }
}
